### ISSUE TITLE
Instructor feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [MadJavaEntJavaSpring2018/MaybeBabyTeamProject2#1]
- [ ] Can you update your readme.md with the various capabilities of your service so I can make sure this is appropriately sized for a team of 4? For example, I would expect your service would have the ability to return a list of possible values for activities to make it easy for a service consumer to know what values are possible. This would also make it easy to build the UI if possible values are provided by the service as an html select. Also think about making the service flexible to allow the consumer to specify the unit type - Metric or US/English.

**Comment by Assoman** [comment]
I added a line to the readme.md describes the return values and formats.

**Comment by Assoman** [comment]
API Documentation updated.
